return {
	AuraInfo = {
		{
			Name = "Common",
			MutationOf = "None",
			OneIn = 2
		},
		{
			Name = "Uncommon",
			MutationOf = "None",
			OneIn = 4
		},
		{
			Name = "Rare",
			MutationOf = "None",
			OneIn = 8
		},
		{
			Name = "Good",
			MutationOf = "None",
			OneIn = 10
		},
		{
			Name = "Great",
			MutationOf = "None",
			OneIn = 16
		},
		{
			Name = "Crystal",
			MutationOf = "None",
			OneIn = 32
		}
	},
	RaritiesInOrder = {2, 4, 8, 10, 16, 32}
}